networks:
  default: #automatically  n/w connect  to services
    extranal: true
    name: roboshop
services:
  mongodb:
    image: mongodb:1
    # networks:
    # - roboshop

  catalogue:
    image: catalogue:1
    depends_on:
    - mongodb
    # networks:
    # - roboshop
  web:
    image: web:1
    ports:
    - "80:80"
    depends_on:
    - catalogue
